-- RESTRICCIONES DE CLAVE PRIMARIA
ALTER TABLE HECHOS
    ADD CONSTRAINT PK_HECHOS PRIMARY KEY (USER_ID, ANIME_ID, GENRE_ID, PRODUCTOR_ID, DATE_ID);

ALTER TABLE ANIME
    ADD CONSTRAINT PK_ANIME PRIMARY KEY (ANIME_ID);

ALTER TABLE USERS
    ADD CONSTRAINT PK_USERS PRIMARY KEY (USER_ID);

ALTER TABLE TYPES
    ADD CONSTRAINT PK_TYPES PRIMARY KEY (ID_TYPE);

ALTER TABLE GENRE
    ADD CONSTRAINT PK_GENRE PRIMARY KEY (ID_GENRE);

ALTER TABLE RATINGS
    ADD CONSTRAINT PK_RATINGS PRIMARY KEY (ID_RATING);

ALTER TABLE PRODUCTORS
    ADD CONSTRAINT PK_PRODUCTORS PRIMARY KEY (ID_PRODUCTOR);

ALTER TABLE COUNTRY
    ADD CONSTRAINT PK_COUNTRY PRIMARY KEY (ID_COUNTRY);

ALTER TABLE DATES
    ADD CONSTRAINT PK_DATES PRIMARY KEY (ID_DATE);


-- RESTRICCIONES DE CLAVE EXTERNA
ALTER TABLE HECHOS
    ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    ADD CONSTRAINT FK_ANIME_ID FOREIGN KEY (ANIME_ID) REFERENCES ANIME(ANIME_ID),
    ADD CONSTRAINT FK_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID_GENRE),
    ADD CONSTRAINT FK_DATES_ID FOREIGN KEY (DATE_ID) REFERENCES DATES(ID_DATE),
    ADD CONSTRAINT FK_PRODUCTOR_ID FOREIGN KEY (PRODUCTOR_ID) REFERENCES PRODUCTORS(ID_PRODUCTOR);


ALTER TABLE ANIME
    ADD CONSTRAINT FK_ID_TYPE FOREIGN KEY (ID_TYPE) REFERENCES TYPES(ID_TYPE),
    ADD CONSTRAINT FK_ID_RATING FOREIGN KEY (ID_RATING) REFERENCES RATINGS(ID_RATING);


ALTER TABLE USERS 
    ADD CONSTRAINT FK_ID_COUNTRY FOREIGN KEY (LOCATION) REFERENCES COUNTRY(ID_COUNTRY)