-- Restricciones de clave primaria
ALTER TABLE HECHOS
ADD CONSTRAINT pk_hechos PRIMARY KEY (USER_ID, ANIME_ID, DATE_RATING);

ALTER TABLE ANIME
ADD CONSTRAINT pk_anime PRIMARY KEY (ANIME_ID);

ALTER TABLE USERS
ADD CONSTRAINT pk_users PRIMARY KEY (USER_ID);

ALTER TABLE TYPES
ADD CONSTRAINT pk_types PRIMARY KEY (ID_TYPE);

ALTER TABLE GENRE
ADD CONSTRAINT pk_genre PRIMARY KEY (ID_GENRE);

ALTER TABLE RATINGS
ADD CONSTRAINT pk_ratings PRIMARY KEY (ID_RATING);

ALTER TABLE PRODUCTORS
ADD CONSTRAINT pk_productors PRIMARY KEY (ID_PRODUCTOR);

-- Restricciones de clave externa
ALTER TABLE HECHOS
ADD CONSTRAINT fk_user_id FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
ADD CONSTRAINT fk_anime_id FOREIGN KEY (ANIME_ID) REFERENCES ANIME(ANIME_ID),
ADD CONSTRAINT fk_genre_id FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID_GENRE),
ADD CONSTRAINT fk_productor_id FOREIGN KEY (PRODUCTOR_ID) REFERENCES PRODUCTORS(ID_PRODUCTOR);

ALTER TABLE ANIME
ADD CONSTRAINT fk_id_genre FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE),
ADD CONSTRAINT fk_id_type FOREIGN KEY (ID_TYPE) REFERENCES TYPES(ID_TYPE),
ADD CONSTRAINT fk_id_rating FOREIGN KEY (ID_RATING) REFERENCES RATINGS(ID_RATING);
