DROP DATABASE IF EXISTS anime_olap;
CREATE DATABASE anime_olap;
USE anime_olap;


DROP TABLE IF EXISTS HECHOS;
CREATE TABLE HECHOS
(
    USER_ID INT,
    ANIME_ID INT,
    DATE_RATING INT,
    GENRE_ID INT,
    PRODUCTOR_ID INT,
    DATE_ID INT,
    RATING INT 
);

DROP TABLE IF EXISTS ANIME;
CREATE TABLE ANIME
(
    ANIME_ID INT,
    ANIME_NAME VARCHAR(255),
    EPISODES INT,
    EMISION_STATUS VARCHAR(255),
    SOURCE VARCHAR(255),
    POPULARITY FLOAT,
    FAVORITES FLOAT,
    MEMBERS FLOAT,
    EMISSION DATETIME,
    CLOSURE DATETIME,
    ID_TYPE INT,
    ID_RATING INT
);


-- USERS
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    USER_ID INT,
    JOINED DATETIME,
    DAYS_WATCHED FLOAT,
    WATCHING FLOAT,
    COMPLETED FLOAT,
    ON_HOLD FLOAT,
    DROPPED FLOAT,
    EPISODES_WATCHED FLOAT,
    LOCATION INT

);



-- TYPE
DROP TABLE IF EXISTS TYPES;
CREATE TABLE TYPES
(
    ID_TYPE INT,
    CODE VARCHAR(5),
    FULL_DESCRIPTION TEXT

);

-- GENRE
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID_GENRE INT,
    GENRE VARCHAR(30)

);

-- RATINGS
DROP TABLE IF EXISTS RATINGS;
CREATE TABLE RATINGS
(
    ID_RATING INT,
    RATING FLOAT,
    CODE VARCHAR(5)

);


-- PRODUCTORS
DROP TABLE IF EXISTS PRODUCTORS;
CREATE TABLE PRODUCTORS
(
    ID_PRODUCTOR INT,
    NAME VARCHAR(255)

);


-- COUNTRY
DROP TABLE IF EXISTS COUNTRY;
CREATE TABLE COUNTRY
(
    ID_COUNTRY INT,
    NAME VARCHAR(50)
);


-- DATES
DROP TABLE IF EXISTS DATES;
CREATE TABLE DATES
(
    ID_DATE INT,
    ISO_WEEK INT, 
    MONTH INT, 
    TRIMESTER INT, 
    SEMESTER INT, 
    YEAR INT
);