USE anime_olap;

ALTER TABLE GENRE
ADD PRIMARY KEY (ID_GENRE);

ALTER TABLE ANIME
ADD PRIMARY KEY (ID_ANIME);

ALTER TABLE CLASSIFICATION
ADD PRIMARY KEY (ID_CLASSIFICATION);

ALTER TABLE SOURCES
ADD PRIMARY KEY (ID_SOURCES);

ALTER TABLE TYPES
ADD PRIMARY KEY (ID_TYPES);

ALTER TABLE USERS
ADD PRIMARY KEY (ID_USER);

ALTER TABLE GENRE_ANIME
ADD PRIMARY KEY (ID_ANIME, ID_GENRE);

ALTER TABLE ANIME_HECHOS
ADD PRIMARY KEY (ID_ANIME, ID_CLASSIFICATION, ID_SOURCES, ID_USER, ID_TYPES);


ALTER TABLE GENRE_ANIME
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE);


ALTER TABLE ANIME_HECHOS
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_CLASSIFICATION) REFERENCES CLASSIFICATION(ID_CLASSIFICATION),
ADD FOREIGN KEY (ID_SOURCES) REFERENCES SOURCES(ID_SOURCES),
ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER),
ADD FOREIGN KEY (ID_TYPES) REFERENCES TYPES(ID_TYPES);
