DROP DATABASE IF EXISTS anime_olap;
CREATE DATABASE anime_olap;

USE anime_olap;

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (
  ID_GENRE INT NOT NULL,
  GENRE VARCHAR(30)
);

DROP TABLE IF EXISTS ANIME;
CREATE TABLE ANIME (
  ID_ANIME INT NOT NULL,
  ANIME_NAME VARCHAR(255),
  FAVORITES FLOAT,
  START_DATE DATE,
  FINISH_DATE DATE
);

DROP TABLE IF EXISTS CLASSIFICATION;
CREATE TABLE CLASSIFICATION (
  ID_CLASSIFICATION INT NOT NULL,
  CLASSIFICATION VARCHAR(30)
);

DROP TABLE IF EXISTS SOURCES;
CREATE TABLE SOURCES (
  ID_SOURCES INT NOT NULL,
  SOURCES VARCHAR(30)
);

DROP TABLE IF EXISTS TYPES;
CREATE TABLE TYPES (
  ID_TYPES INT NOT NULL,
  TYPES VARCHAR(50)
);

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  ID_USER INT NOT NULL,
  USERNAME VARCHAR(50),
  LOCATION VARCHAR(255),
  COMPLETED FLOAT,
  DROPPED FLOAT,
  PLAN_TO_WATCH FLOAT,
  WATCHING FLOAT
);

DROP TABLE IF EXISTS GENRE_ANIME;
CREATE TABLE GENRE_ANIME(
	ID_ANIME INT NOT NULL,
	ID_GENRE INT NOT NULL
);

DROP TABLE IF EXISTS ANIME_HECHOS;
CREATE TABLE ANIME_HECHOS(
	ID_ANIME INT NOT NULL,
	ID_CLASSIFICATION INT NOT NULL,
	ID_SOURCES INT NOT NULL,
	ID_USER INT NOT NULL,
	ID_TYPES INT NOT NULL,
	RATING INT
);
