USE anime_oltp;

-- Tabla ANIME
ALTER TABLE ANIME
ADD PRIMARY KEY (ID_ANIME);

-- Tabla GENRE
ALTER TABLE GENRE
ADD PRIMARY KEY (ID_GENRE);

-- Tabla CLASSIFICATION
ALTER TABLE CLASSIFICATION
ADD PRIMARY KEY (ID_CLASIFICATION);

-- Tabla SOURCES
ALTER TABLE SOURCES
ADD PRIMARY KEY (ID_SOURCES);

-- Tabla TYPES
ALTER TABLE TYPES
ADD PRIMARY KEY (ID_TYPES);

-- Tabla USERS
ALTER TABLE USERS
ADD PRIMARY KEY (ID_USER);

-- Tabla TYPE_RELATION
ALTER TABLE TYPE_RELATION
ADD PRIMARY KEY (ID_TYPE_RELATION);

-- Tabla RATINGS
ALTER TABLE RATINGS
ADD PRIMARY KEY (ID_ANIME, ID_USER);

-- Tabla RATINGS
ALTER TABLE GENRE_ANIME 
ADD PRIMARY KEY (ID_ANIME, ID_GENRE);

-- Tabla ANIME_RELATION
ALTER TABLE ANIME_RELATION
ADD PRIMARY KEY (ID_ORIGEN, ID_RELATION, ID_TYPE_RELATION);


-- Tabla ANIME
ALTER TABLE ANIME
ADD FOREIGN KEY (ID_CLASSIFICATION) REFERENCES CLASSIFICATION(ID_CLASIFICATION),
ADD FOREIGN KEY (ID_SOURCES) REFERENCES SOURCES(ID_SOURCES),
ADD FOREIGN KEY (ID_TYPES) REFERENCES TYPES(ID_TYPES);

-- Tabla GENRE_ANIME
ALTER TABLE GENRE_ANIME
ADD FOREIGN KEY (ID_GENRE) REFERENCES GENRE(ID_GENRE),
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME);

-- Tabla RATINGS
ALTER TABLE RATINGS
ADD FOREIGN KEY (ID_ANIME) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER);

-- Tabla ANIME_RELATION
ALTER TABLE ANIME_RELATION
ADD FOREIGN KEY (ID_ORIGEN) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_RELATION) REFERENCES ANIME(ID_ANIME),
ADD FOREIGN KEY (ID_TYPE_RELATION) REFERENCES TYPE_RELATION(ID_TYPE_RELATION);




