USE anime_oltp;

-- ANIME
ALTER TABLE anime
ADD PRIMARY KEY (ANIME_ID);

-- GENRE
ALTER TABLE genre
ADD PRIMARY KEY (ID_GENRE);

-- CLASIFICATION
ALTER TABLE classification
ADD PRIMARY KEY (ID_CLASIFICATION);

-- SOURCE
ALTER TABLE source
ADD PRIMARY KEY (ID_SOURCE);



-- FORANEAS ANIME
ALTER TABLE anime
ADD CONSTRAINT fk_classification
FOREIGN KEY (ID_CLASIFICATION) REFERENCES classification(ID_CLASIFICATION),
ADD CONSTRAINT fk_source
FOREIGN KEY (ID_SOURCE) REFERENCES source(ID_SOURCE);

-- GENRE ANIME
ALTER TABLE genre_anime
ADD CONSTRAINT fk_genre
FOREIGN KEY (ID_GENRE) REFERENCES genre(ID_GENRE),
ADD CONSTRAINT fk_anime
FOREIGN KEY (ID_ANIME) REFERENCES anime(ANIME_ID);

-- anime_relation

ALTER TABLE anime_relation
ADD CONSTRAINT fk_origen
FOREIGN KEY (ID_ORIGEN) REFERENCES anime(ANIME_ID),
ADD CONSTRAINT fk_relacion
FOREIGN KEY (ID_RELATION) REFERENCES anime(ANIME_ID);
