-- BORRAR BASE SI EXISTE
DROP DATABASE IF EXISTS anime_oltp;
CREATE DATABASE anime_oltp;
USE anime_oltp;

-- Creación de la tabla `anime`
DROP TABLE IF EXISTS ANIME;
CREATE TABLE ANIME (
  ID_ANIME         INT NOT NULL,
  ANIME_NAME        VARCHAR(255),
  EPISODES          INT,
  URL_IMAGE         VARCHAR(255),
  DURATION          TIME,
  FAVORITES			FLOAT,
  SYNOPSIS          TEXT,
  STATUS            VARCHAR(30),
  START_DATE        DATE,
  FINISH_DATE       DATE,
  ID_CLASSIFICATION  INT NOT NULL,
  ID_SOURCES        INT NOT NULL,
  ID_TYPES			INT NOT NULL
);

-- Creación de la tabla `genre`
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE (
  ID_GENRE  INT NOT NULL,
  GENRE     VARCHAR(30)
);

-- Creación de la tabla `genre_anime`
DROP TABLE IF EXISTS GENRE_ANIME;
CREATE TABLE GENRE_ANIME (
  ID_GENRE  INT NOT NULL,
  ID_ANIME INT NOT NULL
);

-- Creación de la tabla `classification`
DROP TABLE IF EXISTS CLASSIFICATION;
CREATE TABLE CLASSIFICATION (
  ID_CLASIFICATION  INT NOT NULL,
  CLASIFICATION     VARCHAR(30)
);

-- Creación de la tabla `source`
DROP TABLE IF EXISTS SOURCES;
CREATE TABLE SOURCES(
  ID_SOURCES  INT NOT NULL,
  SOURCES     VARCHAR(30)
);

-- CREACIONN DE TYPES
DROP TABLE IF EXISTS TYPES;
CREATE TABLE TYPES(
	ID_TYPES INT NOT NULL,
	TYPES VARCHAR(50)
);

-- creacion de tabla user
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
	ID_USER 			INT NOT NULL,
	USERNAME			VARCHAR(50),
	GENDER				VARCHAR(50),
	BIRTHDAY			DATE,
	LOCATION			VARCHAR(50),
	JOINED				DATE,
	DAYS_WATCHED		FLOAT,
	WACHINH				FLOAT,
	COMPLETED			FLOAT,
	ON_HOLD				FLOAT,
	DROPPED				FLOAT,
	PLAN_TO_WATCH		FLOAT,
	REWACHED			FLOAT,
	EPISODES_WATCHED	FLOAT
);

-- CREACION DE RATINGS
DROP TABLE IF EXISTS RATINGS;
CREATE TABLE RATINGS(
	ID_ANIME INT NOT NULL,
	ID_USER INT NOT NULL,
	RATING INT
);

-- CREACION TYPE_RELATION
DROP TABLE IF EXISTS TYPE_RELATION;
CREATE TABLE TYPE_RELATION(
	ID_TYPE_RELATION INT NOT NULL,
	TYPE_RELATION VARCHAR(255)
);

-- Creación de la tabla `anime_relation
DROP TABLE IF EXISTS ANIME_RELATION;
CREATE TABLE ANIME_RELATION (
  ID_ORIGEN  			INT NOT NULL,
  ID_RELATION			INT NOT NULL,
  ID_TYPE_RELATION		INT NOT NULL
);

