USE anime_oltp;

-- ANIME
ALTER TABLE ANIME ADD 
    PRIMARY KEY (ANIME_ID);

-- WATCHED_ANIMES
ALTER TABLE WATCHED_ANIMES ADD 
    PRIMARY KEY (USER_ID, ANIME_ID);

-- TYPE
ALTER TABLE TYPE ADD 
    PRIMARY KEY (ID_TYPE);

-- GENRE
ALTER TABLE GENRE ADD 
    PRIMARY KEY (ID_GENRE);

-- RATINGS
ALTER TABLE RATING ADD 
    PRIMARY KEY (ID_RATING);

-- ANIME_PRODUCTORS
ALTER TABLE ANIME_PRODUCTORS ADD 
    PRIMARY KEY (ID_PRODUCTOR, ID_ANIME);

-- USERS
ALTER TABLE USERS ADD 
    PRIMARY KEY (USER_ID);

-- PRODUCTORS
ALTER TABLE PRODUCTORS ADD 
    PRIMARY KEY (ID_PRODUCTOR);


-- ---------------------------------------------------------------
-- FOREIGN KEYS --
-- ---------------------------------------------------------------

-- ANIME

ALTER TABLE ANIME ADD
    FOREIGN KEY (ID_TYPE) 
        REFERENCES TYPE(ID_TYPE);

ALTER TABLE ANIME ADD
    FOREIGN KEY (ID_GENRE) 
        REFERENCES GENRE(ID_GENRE);

ALTER TABLE ANIME ADD
    FOREIGN KEY (ID_RATING) 
        REFERENCES RATINGS(ID_RATING);

-- WATCHED_ANIMES

ALTER TABLE WATCHED_ANIMES ADD
    FOREIGN KEY (USER_ID) 
        REFERENCES USERS(USER_ID);

ALTER TABLE WATCHED_ANIMES ADD
    FOREIGN KEY (ANIME_ID) 
        REFERENCES ANIMES(ANIME_ID);

-- ANIME_PRODUCTORS

ALTER TABLE ANIME_PRODUCTORS ADD
    FOREIGN KEY (ID_PRODUCTOR) 
        REFERENCES PRODUCTORS(ID_PRODUCTOR);

ALTER TABLE ANIME_PRODUCTORS ADD
    FOREIGN KEY (ID_ANIME) 
        REFERENCES ANIMES(ANIME_ID);

