-- BORRAR BASE SI EXISTE
DROP DATABASE IF EXISTS anime_oltp;
CREATE DATABASE anime_oltp;
USE anime_oltp;


-- ANIME
DROP TABLE IF EXISTS ANIME;
CREATE TABLE ANIME
(
    ANIME_ID INT, 
    ANIME_NAME VARCHAR(255),
    SCORE FLOAT,
    SYNOPSIS TEXT,
    EPISODES INT,
    PREMIERE DATETIME,
    EMISION_STATUS VARCHAR(255),
    PRODUCERS VARCHAR(255),
    SOURCE VARCHAR(255),
    ANIME_RANK FLOAT,
    POPULARITY FLOAT,
    FAVORITES FLOAT,
    SCORED_BY FLOAT,
    MEMBERS FLOAT,
    IMAGE_URL VARCHAR(255),
    EMISION DATETIME,
    CIERRE DATETIME,
    ID_GENRE VARCHAR(255),
    ID_RATING INT

);


-- USERS
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    USER_ID INT,
    USER_NAME VARCHAR(255),
    JOINED DATETIME,
    DAYS_WATCHED FLOAT,
    MEAN_SCORE FLOAT,
    WATCHING FLOAT,
    COMPLETED FLOAT,
    ON_HOLD FLOAT,
    DROPPED FLOAT,
    PLAN_TO_WATCH FLOAT,
    TOTAL_ENTRIES FLOAT,
    REWATCHED FLOAT,
    EPISODES_WATCHED FLOAT

);

-- WATCHED_ANIMES
DROP TABLE IF EXISTS WATCHED_ANIMES;
CREATE TABLE WATCHED_ANIMES
(
    USER_ID INT, 
    ANIME_ID INT, 
    RATING INT

);

-- TYPE
DROP TABLE IF EXISTS TYPE;
CREATE TABLE TYPE
(
    ID_TYPE INT, 
    CODE VARCHAR(5), 
    FULL_DESCRIPTION VARCHAR(50)

);

-- GENRE
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE
(
    ID_GENRE INT, 
    GENRE VARCHAR(30) 

);

-- RATINGS
DROP TABLE IF EXISTS RATINGS;
CREATE TABLE RATINGS
(
    ID_RATING INT, 
    RATING FLOAT, 
    CODE VARCHAR(5)

);

-- ANIME_PRODUCTORS
DROP TABLE IF EXISTS ANIME_PRODUCTORS;
CREATE TABLE ANIME_PRODUCTORS
(
    ID_PRODUCTOR INT, 
    ID_ANIME INT

);

-- PRODUCTORS
DROP TABLE IF EXISTS PRODUCTORS;
CREATE TABLE PRODUCTORS
(
    ID_PRODUCTOR INT, 
    NAME VARCHAR(255)

);



